CREATE TABLE [dbo].[Instructions]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Active] BIT NOT NULL DEFAULT(0),
	[Type] NVARCHAR(256) NOT NULL,
	[Amount] DECIMAL(36,8) NOT NULL,
    [ConversionRate] DECIMAL(36,8) NOT NULL,
	[MonetaryFee] DECIMAL(36,8) NOT NULL DEFAULT(0),
	[MakeTransactionFee] DECIMAL(36,8) NOT NULL DEFAULT(0),
	[UserId] INT NOT NULL,
	[WalletAddressId] INT NULL,
	[WhitelistAddressId] INT NULL,
	[ParentInstructionId] INT NULL,
	[SystemWalletAddressId] INT NULL,
	[FailedDate] DATETIME NULL,
	[FailedReason] NVARCHAR(MAX) NULL,
	[FromDate] DateTime NOT NULL,
	[ToDate] DATETIME NOT NULL,
	[PickedUpDate] DateTime NULL,
	[CompletedDate] DateTime NULL,
	[CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(), 
    [CreatedById] INT NULL,
    [UpdatedDate] DATETIME NULL, 
    [UpdatedById]  INT NULL, 
    CONSTRAINT [FK_Instructions_ToInstructions] FOREIGN KEY ([ParentInstructionId]) REFERENCES [Instructions]([Id]), 
    CONSTRAINT [FK_Instructions_ToWhitelistAddresses] FOREIGN KEY ([WhitelistAddressId]) REFERENCES [WhitelistAddresses]([Id]), 
    CONSTRAINT [FK_Instructions_ToSystemWalletAddresses] FOREIGN KEY ([SystemWalletAddressId]) REFERENCES [SystemWalletAddresses]([Id]), 
)
